### ISSUE TITLE
[BUG] datetime long format output [must be shorter]

### ISSUE THREAD

**Issue by 0xk4b1r** [thecyberworld/port-scanner#26]
### Describe the bug

datetime long format output must be shorter.
The issue is at the time started and at the end (scanning completed in: ) 

after the decimal point numbers should be excluded.

### To Reproduce

before and after the process got completed,

### Expected Behavior

datetime module is providing the long time format, that must be in short

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/44284877/180652974-2fa84c53-5882-45c1-b89d-33c6b6bff08c.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mr4s** [comment]
@kabir0x23 I would love to contribute on this issue

**Comment by 0xk4b1r** [comment]
> @kabir0x23 I would love to contribute on this issue

that's nice, i am assigning you this issue

can you please check out this one first:
https://github.com/CryptoverseWeb3/git-github-practice

**Comment by mr4s** [comment]
> > @kabir0x23 I would love to contribute on this issue
> 
> that's nice, i am assigning you this issue
> 
> can you please check out this one first: https://github.com/CryptoverseWeb3/git-github-practice

Done

**Comment by 0xk4b1r** [comment]
> @kabir0x23 I would love to contribute on this issue

assigned to you ✅
